name: Deploy .NET App to Azure Web App (develop branch)

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Hoặc phiên bản phù hợp với dự án

      - name: Restore dependencies
        run: dotnet restore src/DeliveryNotification/DeliveryNotification.csproj

      - name: Build project
        run: dotnet build --configuration Release --no-restore src/DeliveryNotification/DeliveryNotification.csproj

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish --no-build src/DeliveryNotification/DeliveryNotification.csproj

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'notification-price'  # Tên App Service của bạn
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
